### ISSUE TITLE
Fileinput bar error 

### ISSUE THREAD

**Issue by mmoralesIG** [rstudio/shiny#3179]
Hi, it seems like this issue is been going on for a long time

I'm using fileinput to upload (multiple) images. In desktop, it works without a problem

````
fileInput("fotos_bundle", "", accept = c('image/png', 'image/jpeg'),multiple = TRUE )
````

But in shinyapps after deployed, I just found (after several runs) that ONE particular image triggered a problem
this happens in the status progress bar, in red
````
<!DOCTYPE HTML><html lang="en"><head><title>Error</title><style type="text/css"> body { color: #222; background: #ddd; font-family: sans-serif; margin: 20px; } h1, h2, pre { margin: 20px; } .box ..... and so on
````

there's nothing  special about this, it's just another picture. 

So, it seems it's a bug in shinyapps.io, it's out of my control, isn't?

### System details

Browser Version: 

Output of `sessionInfo()`:

```
# sessionInfo() output goes here
```

### Example application *or* steps to reproduce the problem

 

```R
# Minimal, self-contained example app code goes here
```

**Comment by dcaud** [comment]
I get the same error when uploading an xlsx doc. The error doesn't occur locally, but only on shinyapps.io. There is no info in the log files on shinyapps.io.

My issue is very similar to this unresolved question:

https://stackoverflow.com/questions/49825288/error-deploying-shiny-app-that-uses-fileinput-to-upload-data

Please help!

**Comment by stevepowell99** [comment]
Same here with uploading an xlsx file, works locally but not on shinyapps.io. If I cut most of the rows off the file, it's fine. This is in spite of having set `options(shiny.maxRequestSize = 300*1024^2)`. I can't work out what files are not accepted and what are.

**Comment by PitBosch** [comment]
Same here, uploading a csv. only one out of 100. Can't figure out how to solve

**Comment by mmoralesIG** [comment]
I found in other place that it seems to be an internal bug, so, no solution so far.
My error still happens every now and then with some pictures taken with some cellphones under certain characteristics (so, no idea)

for the ones with xlsx, try using openxlsx, I hope that works

**Comment by stevepowell99** [comment]
@mmoralesIG do you have a link to the other place with info about the internal bug?

**Comment by LVVbc** [comment]
@mmoralesIG did switching to openxlsx resolve the issue for you? I've been running into this exact issue and haven't been able to find a workaround. Reading excel files with openxlsx instead of readxl didn't seem to fix it for me

**Comment by LVVbc** [comment]
I submitted a ticket to RStudio support. Here's the response I received:

This looks like a known bug in shinyapps.io involving uploading certain files. The development team is aware of the problem, but a fix has not yet been scheduled. For now, you may be able to work around this by changing the file encoding (files encoded in UTF-8 are less likely to fail) or by zipping the files first and adding code to unzip them on the server to work around this. Otherwise, we'll let you know once we have a fix in place

**Comment by dcaud** [comment]
@LVVbc I got the same response from RStudio approx. 1 year ago... don't hold your breath. BTW, the workaround puts an untenable onus on the user to convert files before uploading, so it doesn't really work

**Comment by pythiantech** [comment]
Has this been resolved? I am also facing the same issue

**Comment by LVVbc** [comment]
@pythiantech not that I'm aware of. If you contact Rstudio support hopefully that will elevate the issue for them

**Comment by torbjornso** [comment]
I have the same issue, uploading an html file containing a table. Works fine on my computer, and other, similar files, work, but some just fail.

**Comment by jcheng5** [comment]
Can somebody send an example of a file that can’t be uploaded? Or email it to me at joe@rstudio.com

**Comment by wch** [comment]
@jcheng5 This sounds like it's the same as #991. In the discussion there, I have an example app with file upload, and there is an image in the thread which, if you try to upload it, results in an error.

**Comment by wch** [comment]
Hi all, the underlying issue should be fixed, and these file uploads should work now. Sorry that it has taken so long to address!

**Comment by chrisd31** [comment]
@wch could you please share what the fix was? I might be having a similar issue but with uploading pdfs running in a container.

**Comment by wch** [comment]
@chrisd31 I don't know much about the technical details, but I do know that it had something to do with some proxying code that is used only on shinyapps.io. That code isn't public, so it wouldn't be causing your issue.

**Comment by djacob65** [comment]
Hi,

I have the same problem but on a VM installed in a datacenter managed by OpenStack. I have root rights on my VM. I tried tuning the nginx server, in particular the keepAlive parameters, but still the same problem. The size of ZIP files in my situation seems to be limited to 18MB. Above that it doesn't work anymore. I am still searching a solution ...

**Comment by djacob65** [comment]
I solved my issue by putting in global.R file, the following line :

options(shiny.jquery.version = 1)

See https://shiny.rstudio.com/reference/shiny/1.4.0/upgrade.html

**Comment by djacob65** [comment]
Oops ! Sorry. Actually this doesn't solve my problem. But I managed to resolve my problem by stopping docker, then deleting the /var/lib/docker directory then restarting docker. I then reloaded my image from dockerhub, and it worked.
