### ISSUE TITLE
pickerInput (bootstrap-select shiny-bound-input)  selection box will not close.

### ISSUE THREAD

**Issue by wyldsoul** [rstudio/shiny#3281]
### Example application *or* steps to reproduce the problem

 

He are the reproducible examples that illustrate the issue described below.

https://shinyapps.fau.edu/example-shiny1-5-0/app/MTCars2 (works as expected)

https://shinyapps.fau.edu/example-shiny1-6-0/app/MTCars (has issue)

```R
# Minimal, self-contained example app code goes here
```

### Describe the problem in detail

When a user clicks inside a pickerInput dropdown, a box opens with a list of choices.  After a user makes a selection, or left clicks outside the box,  the box with the choices remains open.  Only several left clicks, a right click, or the escape key will close the box. 
It appears that the issue is that the bootstrap-select shiny-bound-input gets stuck open, and the aria-expanded property is stuck on true.  When a user left clicks, the box briefly disappears, shiny-bound-input closes and area-expanded=false, but then then quickly return to open and true.

![bootstrapselect_issue](https://user-images.githubusercontent.com/13875446/106803488-48295b80-6632-11eb-8d11-48bf368357be.PNG)

I generated 2 example applications deployed via shinyproxy docker containers to illustrate the differences the issue. The code bases are identical for each app, other than one has shiny 1.5.0 and one has shiny 1.6.0.  The html dependencies that change between example-shiny1-5-0/app/MTCars2  and  example-shiny1-6-0/app/MTCars are as follows:
* shiny[1.5.0] replaced with shin-css[1.6.0]
* shiny-javascript[1.6.0] added to 1-6-0
* json2[2014.02.04] removed from 1-6-0
All other dependencies are identical.

https://shinyapps.fau.edu/example-shiny1-5-0/app/MTCars2 
This application uses shiny 1.5.0.  When a use clicks inside a pickerInput dropdown, a box opens with a list of choices.  When a user makes a selection or left clicks anywhere outside of this box, the box closes. 

https://shinyapps.fau.edu/example-shiny1-6-0/app/MTCars
This application uses shiny 1.5.0.  The pickerInput box does not close after a choice is made, or when a user clicks outside of the box.

**Comment by wch** [comment]
This sounds like a duplicate of:
https://github.com/rstudio/shiny/issues/3266

Also filed here:
https://github.com/dreamRs/shinyWidgets/issues/346

Fixed by:
https://github.com/rstudio/bslib/pull/241

You can install the development version of bslib with:

```R
remotes::install_github("rstudio/bslib")
```

**Comment by cpsievert** [comment]
If the app is using vanilla shiny (i.e., it's not using bslib), then you'll actually want to install the development version of shiny, not bslib:

```r
remotes::install_github("rstudio/shiny")
```

**Comment by wyldsoul** [comment]
Thank you.  I am not using bslib currently, however, I just deployed the shiny-1-6-0 version of the application with 
remotes::install_github("rstudio/bslib") and the pickerInput now functions as expected.  I will try using just the dev shiny.

**Comment by kaijagahm** [comment]
For anyone reading this and having the same problem––remember to restart R after installing the dev versions of bslib/shiny as noted above. I was facing this problem, and installing the dev versions didn't fix it until I restarted--but now that I've restarted it's working fine :)

Thanks @wch and @cpsievert for fixing this!
