### ISSUE TITLE
Update of shiny leafes leaflet without circles.

### ISSUE THREAD

**Issue by Make42** [rstudio/shiny#863]
This morning my app ran smoothly and as it should. Then I updated shiny. Now my app still runs "smoothly", but without showing any circles on my leaflet map...

I can see that everything else seems to work, because my ggplot graphic, which depends on exactly the same slidersInputs and selectInput is running as it should.

No errors are thrown.

The interesting code is:

      observe({

       # 1) remove old circles:
          leafletProxy("mapplot") %>%
            clearShapes()
    
       # 2) add new circles:
          leafletProxy("mapplot", data = grid()) %>%
            addCircles(opacity = 1, color = pal()(grid()$density))

        })

When I comment block 1, the circles are shown, but so are all circles which have been printed ever before - overlapping each other. If I uncomment block 1, first no circles are shown - then, after the first manipulation of one of my inputs, circles are shown - then, after any further manipulation, no circles are shown anymore.

It can not be that grid() is not providing data, since data is shown when bock 1 is commented.

**Comment by jcheng5** [comment]
Did you update shiny to the most recent CRAN release or to the GitHub master? If the former, it's a bug that we've fixed--you can work around it if possible by putting clearShapes() and addCircles() calls on the same leafletProxy() call.

```r
leafletProxy("mapplot") %>%
  clearShapes() %>%
  addCircles(opacity = 1, color = pal()(grid()$density))
```

Thanks!

**Comment by Make42** [comment]
Your code does not work - if I am correct it does not work by design. That was my original code from last week, and I changed to my code above, because of it. The reason seems to be to me, that the clearShapes() is "stronger" than the addCircles() and clears those away as well.

However, I could solve the issue still, by running

      devtools::install_github('rstudio/shiny')

as you suggested. Thank you.

**Comment by jcheng5** [comment]
There's no notion of "stronger"--the commands are supposed to be executed in order.

I've located the issue and fixed it in https://github.com/rstudio/leaflet/commit/58d32f339ca19c42ba55eb3b1c1d65baf5c073ea. The problem was that I previously assumed that the fix on master would be included in Shiny 0.12.1, so leaflet would only work around Shiny's bug if the version was earlier than that. But it turned out we needed to do a hurry-up release of 0.12.1 with just two critical fixes, so 0.12.1 went live without the fix.

I think even your original code should work fine now.

Thanks again, I'm glad you noticed this before we released leaflet to CRAN!
