### ISSUE TITLE
Shiny crash in RStudio using filter_

### ISSUE THREAD

**Issue by zross** [rstudio/shiny#879]
I put this as a stackoverflow question [http://stackoverflow.com/questions/31011159/rstudio-shiny-crashes-when-using-filter-from-dplyr](http://stackoverflow.com/questions/31011159/rstudio-shiny-crashes-when-using-filter-from-dplyr) but it seems to be a Shiny (or RStudio?) issue. 

I'm filtering a dataset using dplyr's filter_ function in a Shiny app. I'm surrounding the evaluation with a try() so that I can catch errors. This works as expected in some situation like, for example, with an empty filter string. But if the filter string includes a variable that is not in the data.frame Shiny crashes entirely.

Take the following code as an example -- if the filter string is just "" Shiny returns an error (as expected). But if you include "z==1" where z does not exist then the app crashes (not expected!).

```r
library(dplyr)
library(shiny)

testapp <- shinyApp(
  ui = bootstrapPage(
    numericInput('n', 'Number of obs', 100),
    plotOutput('plot'),
    uiOutput("whyfail")
  ),

  server = function(input, output) {
    output$plot <- renderPlot({ hist(runif(input$n)) })

    output$whyfail<-renderUI({
      input$n
      dat<-data.frame(a=LETTERS[1:5], b=1:5)
      xx<-try(filter_(dat, ""), silent = TRUE)# returns an error as expected
      #xx<-try(filter_(dat, "z==1"), silent = TRUE) # crashes Shiny
      HTML(paste(attr(xx, "class"), collapse = '<br/>'))
    })
  }
)
runApp(testapp)
```

My version of dplyr is 0.4.2 and shiny is 0.12.1. Two additional details: first, if I run in base R GUI (not RStudio) I don't see the crash. Also, if I don't load dplyr at all the code runs fine with no crash. I am surprised that the code runs given that I would have expected `filter_()` to depend on dplyr and Shiny does not seem to import dplyr or `filter_()`). Rstudio version 0.99.446, R version 3.2.

**Comment by jcheng5** [comment]
What do you mean by crash? Does it kick you back to the R prompt with an
error? Does the R process quit entirely?

**Comment by jcheng5** [comment]
@hadley @kevinushey Any chance this has something to do with the Rcpp change you guys were discussing on Twitter, that stopped suppressMessages from working?

**Comment by kevinushey** [comment]
Seems unlikely -- the regression there is just that calling handlers (e.g. `suppressMessages`) seem to be ignored right now. I'm guessing this is just a memory protection issue in dplyr that only gets bumped when running under shiny.

Odds are this would be reproducible without shiny + with gctorture or some other stress test.

**Comment by jcheng5** [comment]
I'm guessing that "crash" doesn't actually mean segfault but just an error that's not caught, which is surprising in this case because it's in a try(). If calling handlers don't work, does that affect try() as well?

**Comment by jcheng5** [comment]
Oh, also weird that it doesn't happen outside of RStudio though, I don't know what to make of that. Maybe you're right.

**Comment by zross** [comment]
You asked what I mean by crash and it's that the Shiny window closes immediately and it returns me to the prompt (or, if in a browser, it gets greyed out). I have had one other person @jalapic confirm the behavior. By the way, I'm on Windows 7.

**Comment by jalapic** [comment]
I am also on Windows 7 and experienced the same behavior.

**Comment by jmcphers** [comment]
Outside Shiny:

    > dat<-data.frame(a=LETTERS[1:5], b=1:5)
    > xx<-try(filter_(dat, ""), silent = TRUE)# returns an error as expected
    > xx
    [1] "Error in parse(text = x)[[1]] : subscript out of bounds\n"
    attr(,"class")
    [1] "try-error"
    attr(,"condition")
    <simpleError in parse(text = x)[[1]]: subscript out of bounds>
    
    > xx<-try({filter_(dat, "z==1")}, silent = TRUE) # crashes Shiny
    > xx
    [1] "Error : object 'z' not found\n"
    attr(,"class")
    [1] "try-error"
    attr(,"condition")
    <Rcpp::eval_error: object 'z' not found>

When run under Shiny I see the behavior @zross describes (though I see it in both RGui and RStudio, and I always see the `object 'z'` not found` printed on the console after the Shiny app terminates). Perhaps something specific to condition handling for Rcpp error classes? 

    dplyr_0.4.2       shiny_0.12.1.9000

**Comment by wch** [comment]
I think it has something to do with the `try` function itself doing something weird. Here's an example with a bare observer:

```R
dat<-data.frame(a=LETTERS[1:5], b=1:5)

# Without try/tryCatch/withCallingHandlers, this throws an error which is caught by
# the observer/reactive code and turned into a warning. This is as expected:
observe({
  filter_(dat, "z==1")
})
shiny:::flushReact()
# Warning: Unhandled error in observer: object 'z' not found
# observe({
#     filter_(dat, "z==1")
# })


# With try(), the error escapes somehow
observe({
  try(filter_(dat, "z==1"))
})
shiny:::flushReact()
# Error : object 'z' not found


# With tryCatch, the error is caught, as expected
observe({
  tryCatch(filter_(dat, "z==1"), error = function(e) {
    cat("Caught error: ")
    print(e)
  })
})
shiny:::flushReact()
# Caught error: <Rcpp::eval_error: object 'z' not found>
````

**Comment by jcheng5** [comment]
@wch I don't think the error escapes, I think try is just printing it. Add `silent=TRUE` to try, you shouldn't see anything printed.

Crazy that `""` has the correct behavior but `"z==1"` does not.

**Comment by jcheng5** [comment]
Repros for me on Mac in both R.app and RStudio, BTW.

cc @hadley

**Comment by wch** [comment]
@jcheng5 You're right - the error isn't escaping, it's just printing the message.

The same happens in the minimal example below: the `renderText` completes, but something must happen afterward that brings down the app.

```R
library(dplyr)
library(shiny)

shinyApp(
  ui = bootstrapPage(
    textOutput("whyfail")
  ),
  server = function(input, output) {
    output$whyfail<-renderText({
      dat<-data.frame(a=LETTERS[1:5], b=1:5)

      # xx <- try(filter_(dat, ""), silent = TRUE)# returns an error as expected
      xx <- try(filter_(dat, "z==1"), silent = TRUE) # crashes Shiny

      # We do get here - this gets printed out
      print("tried")
    })
  }
)
```

**Comment by jcheng5** [comment]
Even more minimal:

```r
library(httpuv)
library(dplyr)

browseURL("http://localhost:8000/")
runServer("0.0.0.0", 8000, list(
  call = function(req) {
    
    xx <- try(filter_(cars, "z==1"), silent = TRUE)
    print("Got here")
    
    list(
      status = 200L,
      headers = list("Content-Type" = "text/plain"),
      body = "OK"
    )
  }
))
```

**Comment by wch** [comment]
So it's causing httpuv's `runServer` to die? Just throwing this out there, but could it be that there's some Rcpp error state that's getting set and not cleared properly?

**Comment by jcheng5** [comment]
Even more minimal. This should print nothing (as you can confirm by replacing the `filter_` call with almost any other error-raising code).

```r
library(Rcpp)

Rcpp::sourceCpp(code = "
#include <Rcpp.h>

// [[Rcpp::export]]
void exec(Rcpp::Function func) {
  func();
}
")

exec(function() {
  try(filter_(cars, "z==1"), silent = TRUE)
})
```

**Comment by kevinushey** [comment]
Yikes!

FWIW, the main change in `Rcpp` was with `Rcpp_eval`, and was done to ensure C++ destructors would still run even after user interrupts (ie, by preventing C `longjmp`s):

https://github.com/RcppCore/Rcpp/blob/1114c95b6ee38e3ecc4fd0fda24e277e3a1a043c/inst/include/Rcpp/api/meat/Rcpp_eval.h

In other words, we use `R_TopLevelExec` to evaluate the function call (this effectively removes all condition handlers); we do attach our own warning and error recorders so that those get properly 'forwarded' after the call has finished execution.

**Comment by jcheng5** [comment]
If I downgrade from Rcpp 0.11.6 to 0.11.5, and install dplyr 0.4.1 (since the latest 0.4.2 requires Rcpp 0.11.6), then the problem goes away.

I think CallProxy is a clue:
https://github.com/hadley/dplyr/search?utf8=%E2%9C%93&q=callproxy

The verbs that use CallProxy (filter, summarise, arrange) all have the problem, the other verbs that I tried (select, order) do not.

**Comment by jcheng5** [comment]
WTF. Even in Rcpp 0.11.5, this prints an error when it should be silent (right??):

```r
library(Rcpp)

Rcpp::sourceCpp(code = "
#include <Rcpp.h>

// [[Rcpp::export]]
void exec(Rcpp::Function func) {
  func();
}
")

exec(function() {
  try(silent = TRUE, exec(function() {
    stop("hi")
  }))
})
```

**Comment by kevinushey** [comment]
That's bizarre. :/ It definitely seems to me that the error should be suppressed as well.

If you place the `try()` call _before_ the `exec` call then everything does work as expected. Maybe there is something about how `Rcpp::Function` executes that causes it to just discard condition handlers within?

**Comment by kevinushey** [comment]
Even more simple / weird -- calling `stop()` throws an empty error, while `exec(stop)` doesn't throw an error (with `Rcpp 0.11.6`).

**Comment by jcheng5** [comment]
@kevinushey Thanks for filing the Rcpp bug. I've just found out that Rcpp 0.11.6 + dplyr 0.4.1 doesn't repro the original issue, while Rcpp 0.11.6 + dplyr 0.4.2 does. A (very slow) git bisect is under way...

**Comment by jcheng5** [comment]
git bisect shows this as the first bad commit:
https://github.com/hadley/dplyr/commit/7ea10b25b045ac8852d55978d2102400f03f2069

Indeed, if I checkout v0.4.2 and change `Rcpp_eval` back to `Rf_eval` the problem goes away!

**Comment by kevinushey** [comment]
Thanks @jcheng5 -- it looks like this is our MRE for Rcpp:

    exec(function() try(silent = TRUE, exec(function() stop("ouch"))))

**Comment by jcheng5** [comment]
Just so we're clear though:

1) This issue has existed in Rcpp at least since v0.11.5
2) dplyr happened to tickle it in 0.4.2 in a way that it hadn't before
3) Fixing the issue in Rcpp AND/OR reverting the dplyr change will fix this particular manifestation

Does that all sound right?

**Comment by kevinushey** [comment]
Yep, that's entirely correct.

**Comment by kevinushey** [comment]
I have a proposal that should fix this in Rcpp: https://github.com/RcppCore/Rcpp/pull/313; hopefully if this is indeed the right fix we can get a release onto CRAN soon.

**Comment by vnijs** [comment]
Just ran into this problem with dplyr 0.4.2 and `filter_` (see example below). Any updates on a fix or workaround?

```r
library(shiny)
library(dplyr)
server <- function(input, output) {
  output$try_filter <- renderPrint({
    # err <- try(filter_(mtcars, "vs == 1"), silent = TRUE)   ## what should be entered
    # err <- try(filter_(mtcars, vs = 1), silent = TRUE)      ## this doesn't crash shiny
    err <- try(filter_(mtcars, "vs = 1"), silent = TRUE)    ## this does crash shiny
    print(err)
  })
}

ui <- fluidPage(
  verbatimTextOutput("try_filter")
)

shinyApp(ui = ui, server = server)
```

**Comment by vnijs** [comment]
Using do.call to try and generate a logical vector seems to be a workaround. If the expression is valid, pass that to filter. See example, where `sel` is the expression entered in the shiny app.

```r
sel <- dat %>% {try(do.call(with, list(., parse(text = sel))), silent = TRUE)}
```

**Comment by kevinushey** [comment]
This is now resolved with Rcpp 0.12.0; running the first posted example app no longer causes Shiny to stop.

```
> devtools::session_info()
Session info ------------------------------------------------------------------
 setting  value                                      
 version  R version 3.2.0 Patched (2015-04-26 r68264)
 system   x86_64, mingw32                            
 ui       RStudio (0.99.645)                         
 language (EN)                                       
 collate  English_United States.1252                 
 tz       America/Los_Angeles                        

Packages ----------------------------------------------------------------------
 package    * version  date       source        
 assertthat   0.1      2013-12-06 CRAN (R 3.2.0)
 bitops       1.0-6    2013-08-17 CRAN (R 3.2.0)
 DBI          0.3.1    2014-09-24 CRAN (R 3.2.0)
 devtools     1.8.0    2015-05-02 local         
 digest       0.6.8    2014-12-31 CRAN (R 3.2.0)
 dplyr      * 0.4.2    2015-06-16 CRAN (R 3.2.1)
 git2r        0.7      2015-02-23 CRAN (R 3.2.0)
 htmltools    0.2.6    2014-09-08 CRAN (R 3.2.0)
 httpuv       1.3.3    2015-08-04 CRAN (R 3.2.1)
 jsonlite     0.9.16   2015-04-11 CRAN (R 3.2.0)
 lazyeval     0.1.10   2015-01-02 CRAN (R 3.2.0)
 magrittr     1.5      2014-11-22 CRAN (R 3.2.0)
 memoise      0.2.1    2014-04-22 CRAN (R 3.2.0)
 mime         0.3      2015-03-29 CRAN (R 3.2.0)
 R6           2.1.0    2015-07-04 CRAN (R 3.2.1)
 Rcpp         0.12.0   2015-07-25 CRAN (R 3.2.1)
 RCurl        1.95-4.6 2015-04-24 CRAN (R 3.2.0)
 rstudioapi   0.3.1    2015-04-07 CRAN (R 3.2.0)
 rversions    1.0.0    2015-04-22 CRAN (R 3.2.0)
 shiny      * 0.12.2   2015-08-05 CRAN (R 3.2.0)
 XML          3.98-1.1 2013-06-20 CRAN (R 3.2.0)
 xtable       1.7-4    2014-09-12 CRAN (R 3.2.1)
```

**Comment by kevinushey** [comment]
@vnijs, I just tried your example as well and it executed without crashing Shiny on my system.

**Comment by vnijs** [comment]
Thanks @kevinushey. Not sure how I missed upgrading Rcpp. I thought this was related to R(studio) crashes when using `mutate_each` but I guess that is not the case (see https://github.com/hadley/dplyr/issues/1238#issuecomment-128244652 and the example below)

```r
library(dplyr)
dat <- matrix("", nrow = 1000, ncol = 50) %>% as.data.frame
rmiss <- function(x) ifelse(x == "", NA, .)
mutate_each_(dat, funs(rmiss), vars = colnames(dat)) 
```

**Comment by zross** [comment]
Awesome! I can confirm that the code in the first example at the top no longer crashes with an update to Rcpp 0.12.0 AND update to Shiny 0.12.2 (I was still experiencing a crash with Shiny 0.12.1). Great work!

**Comment by vnijs** [comment]
@kevinushey @zross do you know if this has been tested on Windows 10? I got a report about the crash still happening on that platform but can't replicate without buying Windows 10 (my Win 8 license doesn't get the free upgrade)

**Comment by kevinushey** [comment]
I just tried this out on a Windows 10 machine and all seems well; can you ensure that whoever's reported the issue is using the latest versions of Rcpp / shiny / dplyr?

(Note that R is getting the version of Windows wrong here)

```
> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_0.12.2

loaded via a namespace (and not attached):
 [1] R6_2.1.0         rversions_1.0.2  htmltools_0.2.6  tools_3.2.1      rstudioapi_0.3.1
 [6] curl_0.9.2       memoise_0.2.1    Rcpp_0.12.0      xml2_0.1.1       git2r_0.10.1    
[11] jsonlite_0.9.16  digest_0.6.8     xtable_1.7-4     httpuv_1.3.3     mime_0.3        
[16] devtools_1.8.0  
```

**Comment by vnijs** [comment]
Thanks Kevin! Seems the user didn't have shiny 0.12.2 installed. He updated and the issue was resolved on Windows 10. Nice!

Question: dplyr doesn't require Rcpp 0.12.0 at this point and I don't reply on Rcpp directly. Is there a clean way to 'force' the version of Rcpp? I could add it to import in the Description file I guess but that seems a bit odd. I use the code below now but that isn't ideal either. 

```r
if (packageVersion("Rcpp") < "0.12.0") stop(
  "Radiant requires Rcpp >= 0.12.0. ",
  "Please install the latest version of Rcpp from CRAN: ",
  "install.packages('Rcpp', repo = 'http://cran.rstudio.com')"
)
```

**Comment by vnijs** [comment]
@kevinushey Looks like there will be a new release of dplyr very soon that will require Rcpp >= 0.12.0. I believe this issue can be closed.

**Comment by kevinushey** [comment]
@vnijs indeed -- thanks for testing and verifying!
